// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV3KJ7UUSCWXJNCp7oM6N1pMtic3ee3-Q',
    appId: '1:752705294621:web:0abcbc5c9f6e90fc3ad1f4',
    messagingSenderId: '752705294621',
    projectId: 'flutter-firebase-login-9fe3c',
    authDomain: 'flutter-firebase-login-9fe3c.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-9fe3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJgPOjKY5DNlCkfyv3yEvuZ5UpBqfq2sQ',
    appId: '1:752705294621:android:c18bde2c95bf35753ad1f4',
    messagingSenderId: '752705294621',
    projectId: 'flutter-firebase-login-9fe3c',
    storageBucket: 'flutter-firebase-login-9fe3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMeWOMPaCzDvBlRyPfH6qHcCwUJmLyoA',
    appId: '1:752705294621:ios:bbff230948921cba3ad1f4',
    messagingSenderId: '752705294621',
    projectId: 'flutter-firebase-login-9fe3c',
    storageBucket: 'flutter-firebase-login-9fe3c.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMeWOMPaCzDvBlRyPfH6qHcCwUJmLyoA',
    appId: '1:752705294621:ios:bbff230948921cba3ad1f4',
    messagingSenderId: '752705294621',
    projectId: 'flutter-firebase-login-9fe3c',
    storageBucket: 'flutter-firebase-login-9fe3c.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
